FROM node:20-alpine3.18 AS base

WORKDIR /app

FROM base AS builder

COPY package*.json .
COPY tsconfig.json .
COPY . .

RUN npm install 

COPY . .

RUN npm run build



FROM base AS production
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/tsconfig.json ./
RUN npm install --omit=dev
RUN npm cache clean --force
EXPOSE 3000
CMD ["node", "dist/server.js"]